### ISSUE TITLE
How to add runtime dependencies and environment variables 

### ISSUE THREAD

**Issue by arc1986** [mikelangelo-project/capstan-packages#12]
I am building a C native application that has a runtime dependencies with application config-file and the License file (and some environment variables). I have created the shared object, and run.yaml has only limited options, 

```
runtime: native
config_set:
   ################################################################
   ### This is one configuration set (feel free to rename it).  ###
   ################################################################
   myconfig1:
      # REQUIRED
      # Command to be executed in OSv.
      # Note that package root will correspond to filesystem root (/) in OSv image.
      # Example value: /usr/bin/simpleFoam.so -help
      bootcmd: /my_client.so

   # Add as many named configurations as you need
# OPTIONAL
# What config_set should be used as default.
# This value can be overwritten with --runconfig argument.
config_set_default: myconfig1 
```

So, How to add the application environment variables (License file and config files etc..,)

**Comment by miha-plesko** [comment]
Hi @acsdkquery,

environment variables can be added by means of `env:` in the meta/run.yaml:

```yaml
runtime: native
config_set:   
   myconfig1:     
      bootcmd: /my_client.so
      env:
         CONFIG_FILE: /myconf1.txt
         LICENSE_FILE: /mylicense
         PORT: 8000
         ...

config_set_default: myconfig1 
```

Please let me know if this works for you.
