### ISSUE TITLE
issue in node-6.10.2 capstan package

### ISSUE THREAD

**Issue by ukeshkumar** [mikelangelo-project/capstan-packages#16]
Hi,
I am trying to build image based on node-6.10.2. But by default it is taking node-4.4.5 also (for runtime node).
And while executing the the main js file, it is executing with 4.4.5 version instead of 6.10.2 version.

 - Both node binary of version 4.4.5 & 6.10.2 are available in mpm-pkg/bin directory.
 - node symbolic link in mpm-pkg directory is pointing to /bin/libnode-4.4.5.so

I have created node (symbolic link file) points to '/bin/libnode-6.10.2.so' file. I am getting the following error,
symlink /bin/libnode-6.10.2.so /home/ukesh/code/mpm-pkg/node: file exists

I am using the below,
 - Capstan binary :  http://x.k00.fr/3ub70 ->this is the latest Capstan binary (development branch)
 - Packages downloaded using 'capstan pull' command

Could you please help me to resolve this issue ?

**Comment by miha-plesko** [comment]
Hi,

unfortunately `runtime: node` is bound to 4.4.5 at the moment. Could you please try to require the 6.10.2 package manually and then use `runtime: native`?

So in your meta/package.yaml:

```yaml
name: demo
title: demo
author: me
require:
  - node-6.10.2  # <------ require node manually like this
```

and then in meta/run.yaml:

```yaml
runtime: native
config_set:
  app:
    bootcmd: /node /my/server.js  # <------- this is what will be run
config_set_default: app
```

Please let me know if it works!
